### PR TITLE
Tests for user context

### PR DESCRIPTION
**Pull request by gpincheiraa**
## Description

Adding `jest` and `react-testing-library` for run unit tests.
Adding first test suite for run methods exposed in the contexts files that interact with graphql showing examples how mock this cases and how handle the success and failed scenarios

## Checklist

- [x] All tests are passing
- [x] New tests were created to address changes in pr (and tests are passing)
- [x] Updated README and/or documentation, if necessary
- [x] Added myself / the `contributors` array in package.json

Thanks for contributing!

### CODE REVIEW

**Comment by danestves** [comment]
Hi @gpincheiraa you can update the description of the PR and update to the latest commit of the repo?

**Comment by danestves** [comment]
@all-contributors please add @danestves for code, design, maintenance

**Comment by gpincheiraa** [comment]
@danestves done!

**Comment by danestves** [comment]
@all-contributors please add @gpincheiraa for code, test

**Comment by danestves** [comment]
@all-contributors please add @gpincheiraa for code, test

**Comment by danestves** [comment]
Thank you for your contribution, the PR has been merge

**Pull request merged**
